[workspace]
members = ["crates/purr", "crates/purr-common", "crates/purr-core", 'crates/purr-ui', "crates/purr-web"]
resolver = "2"

[workspace.dependencies]
purr-core = { path = "crates/purr-core" }

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
