[workspace]
members = [
  "crates/purr",
  "crates/purr-common",
  "crates/purr-core",
  'crates/purr-ui',
  "crates/purr-wasm",
  "crates/purr-test-utils",
]
resolver = "2"

[workspace.dependencies]
purr-core = { path = "crates/purr-core" }


[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

# Test profiles
[profile.test]
inherits = "dev"
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
incremental = true
codegen-units = 256

[profile.test-opt]
inherits = "test"
opt-level = 2
lto = "thin"

[profile.bench]
inherits = "release"
debug = true
lto = "thin"
