
# https://github.com/zmwangx/rust-ffmpeg/blob/master/.github/workflows/build.yml


name: build
on:
  push:
  # pull_request:
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  build-linux:
    name: Build Linux${{ matrix.cuda && ' - cuda' || '' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cuda: [false, true]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends clang curl pkg-config gcc ca-certificates openssl libssl-dev cmake libc6-dev make wget \
            libavcodec-dev libavformat-dev libavutil-dev libavfilter-dev libavdevice-dev libswscale-dev libswresample-dev \
            llvm
      - name: Install cuda
        if: matrix.cuda == true
        run: |
          # Detect Ubuntu version and set appropriate CUDA repo
          UBUNTU_VERSION=$(lsb_release -rs | tr -d '.')
          if [ "$UBUNTU_VERSION" = "2204" ]; then
            CUDA_REPO="ubuntu2204"
            CUDA_VERSION="12-6"
            CUDA_PATH_VERSION="12.6"
          else
            CUDA_REPO="ubuntu2404"
            CUDA_VERSION="12-9"
            CUDA_PATH_VERSION="12.9"
          fi
          
          wget https://developer.download.nvidia.com/compute/cuda/repos/${CUDA_REPO}/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt update
          sudo apt install -y cuda-toolkit-${CUDA_VERSION}
          CUDA_PATH=/usr/local/cuda-${CUDA_PATH_VERSION}/
          echo "CUDA_PATH=$CUDA_PATH" >> $GITHUB_ENV
          echo "$CUDA_PATH/bin" >> $GITHUB_PATH
          echo "GITHUB_LIBRARY_PATH=$CUDA_PATH/lib64${GITHUB_LIBRARY_PATH:+:$GITHUB_LIBRARY_PATH}" >> $GITHUB_ENV
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt
          targets: x86_64-unknown-linux-gnu
      - name: Build
        run: cargo build --verbose --release ${{ matrix.cuda && ' --features cuda' || '' }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: purr-linux${{ matrix.cuda && '-cuda' || '' }}
          path: |
            target/release/purr*

  build-macos:
    name: Build macOS (metal)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          brew install ffmpeg pkg-config cmake
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          toolchain: stable
      - name: Build
        run: |
          cargo build --release --features metal
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: purr-macos
          path: |
            target/release/purr*


  build-windows:
    name: Build Windows (MSVC, cuda)
    runs-on: windows-2025
    env:
      FFMPEG_DOWNLOAD_URL: https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          $VCINSTALLDIR = $(& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath)
          Add-Content $env:GITHUB_ENV "LIBCLANG_PATH=${VCINSTALLDIR}\VC\Tools\LLVM\x64\bin`n"
          Invoke-WebRequest "${env:FFMPEG_DOWNLOAD_URL}" -OutFile ffmpeg-release-full-shared.7z
          7z x ffmpeg-release-full-shared.7z
          mkdir ffmpeg
          mv ffmpeg-*/* ffmpeg/
          Add-Content $env:GITHUB_ENV "FFMPEG_DIR=${pwd}\ffmpeg`n"
          Add-Content $env:GITHUB_PATH "${pwd}\ffmpeg\bin`n"
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          toolchain: stable
      - uses: ilammy/msvc-dev-cmd@v1.4.1
      - name: Install cuda & cmake
        run: |
          Install-Module -AcceptLicense -Force -Name Microsoft.WinGet.Client -RequiredVersion 0.2.1
          Import-Module -Name Microsoft.WinGet.Client
          Install-WinGetPackage -Id Nvidia.CUDA
          Install-WinGetPackage -Id Kitware.CMake 
          # print env
          if ($env:CUDA_PATH) {
            Write-Host "CUDA_PATH ($($env:CUDA_PATH)) found"
            Add-Content $env:GITHUB_ENV "CUDA_PATH=$($env:CUDA_PATH)`n"
          } else {
            Write-Error "CUDA_PATH ($($env:CUDA_PATH)) not found"
            exit 1
          }
      - name: Build
        run: |
          cargo build --release --features cuda
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: purr-windows-cuda
          path: |
            target/release/purr*
