
# https://github.com/zmwangx/rust-ffmpeg/blob/master/.github/workflows/build.yml


name: build
on:
  push:
  # pull_request:
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  build-linux:
    name: Linux - FFmpeg 7.1 - build, test and lint
    runs-on: ubuntu-latest
    container: jrottenberg/ffmpeg:7.1-ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt update
          apt install -y --no-install-recommends clang curl pkg-config cmake
      - uses: Jimver/cuda-toolkit@master
        id: cuda-toolkit
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Build
        run: |
          cargo build --release
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            target/release/purr*

  build-macos:
    name: macOS - FFmpeg latest - build, test and lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          brew install ffmpeg pkg-config cmake
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Build
        run: |
          cargo build --release
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            target/release/purr*


  build-windows:
    name: Windows - FFmpeg ${{ matrix.ffmpeg_version }} - build, test and lint
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - ffmpeg_version: latest
            ffmpeg_download_url: https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z
      fail-fast: false
    env:
      FFMPEG_DOWNLOAD_URL: ${{ matrix.ffmpeg_download_url }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          $VCINSTALLDIR = $(& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath)
          Add-Content $env:GITHUB_ENV "LIBCLANG_PATH=${VCINSTALLDIR}\VC\Tools\LLVM\x64\bin`n"
          Invoke-WebRequest "${env:FFMPEG_DOWNLOAD_URL}" -OutFile ffmpeg-release-full-shared.7z
          7z x ffmpeg-release-full-shared.7z
          mkdir ffmpeg
          mv ffmpeg-*/* ffmpeg/
          Add-Content $env:GITHUB_ENV "FFMPEG_DIR=${pwd}\ffmpeg`n"
          Add-Content $env:GITHUB_PATH "${pwd}\ffmpeg\bin`n"
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: ilammy/msvc-dev-cmd@v1.4.1
      - uses: Jimver/cuda-toolkit@master
        id: cuda-toolkit
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
      - name: Build
        run: |
          cargo build --release
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            target/release/purr*
