[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router", "desktop"] }
ui = { workspace = true, features = ["desktop"] }

[features]
default = []
desktop = ["dioxus/desktop"]
server = ["dioxus/server"]
